### ISSUE TITLE
t out does not checkout task in not current sheet even when auto_checkout is true

### ISSUE THREAD

**Issue by vlcinsky** [samg/timetrap#79]
This relates to auto_checkout feature described in issue #52 

Content of my `~/.timetrap.yml` file:

``` yaml

---
database_file: /home/javl/.timetrap.db
round_in_seconds: 900
append_notes_delimiter: ! '; '
formatter_search_paths:
- /home/javl/.timetrap/formatters
default_formatter: text
default_command: 
auto_checkout: true
day_length_hours: 8
progress_width: 60
```

So the `auto_checkout` is `true`
I did not touch this configuration for very long time and it used to work without problem.

Switch to sheet `ttt` and check in:

``` bash
$ t s ttt
Switching to sheet "ttt"
$ t in test entry
Checked out of sheet `qqq`.
Checked into sheet `ttt`.
```

Switch to sheet `qqq` and check in:

``` bash
$ t s qqq
Switching to sheet "qqq"
$ t in other test entry
Checked out of sheet "ttt".
Checked into sheet "qqq".
```

Switching back to previous sheet and call `t now`:

``` bash
$ t s -
Switching to sheet "ttt"
$ t now
*ttt: not running
 qqq: 0:00:05 (other test entry)
```

Trying to checkout now:

``` bash
$ t out
No running entry on sheet "ttt".
```

This was supposed to checkout whichever current task was running, but it sounds like a complain.
Check `t now` again

``` bash
javl@zen:~$ t now
*ttt: not running
 qqq: 0:00:10 (other test entry)
```

Yes, the entry on sheet `qqq` is still running.
And as `auto_checkout` is `true`, it was supposed to be stopped.

I am using latest version of timetrap:

``` bash
t --version
t: version dated 2013-12-12 11:02:35 +0100
```
